title: PROJECTNAME Logos
description: >-
  Logos and artwork for PROJECTLOGO and it's hosted projects

# favicon for the site
favicon: assets/img/favicon.png
# primary project logo - used as the logo that will show up in search results
primary_logo: 
# header for the logo - usually this will be the primary logo in a white out version
header_logo: 
# GH repo this is at
github_repo: https://github.com/jmertic/artwork-template
# gradiant colors for the headers: theme_color_1 -> theme_color_2
theme_color_1: 36b0c9
theme_color_2: 159957 
# optionally, specify a header background image
header_image:
# optionally, specify an image for the background of the main section
section_image:
# categories for projects, used in the front matter for each project page
logo_categories:
  - Incubating
  - Adopted
# default category for CLOtributor
clotributor_category_default:

# don't touch ;-)
baseurl: "/"
readme_index:
  with_frontmatter: true
